top_srcdir   = /home/sekharvaana/Desktop/TomacatLoadbalance/httpd-2.2.34
top_builddir = /home/sekharvaana/Desktop/TomacatLoadbalance/httpd-2.2.34
srcdir       = /home/sekharvaana/Desktop/TomacatLoadbalance/httpd-2.2.34/modules
builddir     = /home/sekharvaana/Desktop/TomacatLoadbalance/httpd-2.2.34/modules
VPATH        = /home/sekharvaana/Desktop/TomacatLoadbalance/httpd-2.2.34/modules

SUBDIRS = $(MODULE_DIRS)
CLEAN_SUBDIRS = $(MODULE_CLEANDIRS)

include $(top_builddir)/build/rules.mk

