top_srcdir   = /home/sekharvaana/Desktop/TomacatLoadbalance/httpd-2.2.34
top_builddir = /home/sekharvaana/Desktop/TomacatLoadbalance/httpd-2.2.34
srcdir       = /home/sekharvaana/Desktop/TomacatLoadbalance/httpd-2.2.34/server/mpm/prefork
builddir     = /home/sekharvaana/Desktop/TomacatLoadbalance/httpd-2.2.34/server/mpm/prefork
VPATH        = /home/sekharvaana/Desktop/TomacatLoadbalance/httpd-2.2.34/server/mpm/prefork

LTLIBRARY_NAME    = libprefork.la
LTLIBRARY_SOURCES = prefork.c

include $(top_srcdir)/build/ltlib.mk
