top_srcdir   = /home/sekharvaana/Desktop/TomacatLoadbalance/httpd-2.2.34
top_builddir = /home/sekharvaana/Desktop/TomacatLoadbalance/httpd-2.2.34
srcdir       = /home/sekharvaana/Desktop/TomacatLoadbalance/httpd-2.2.34/modules/dav/lock
builddir     = /home/sekharvaana/Desktop/TomacatLoadbalance/httpd-2.2.34/modules/dav/lock
VPATH        = /home/sekharvaana/Desktop/TomacatLoadbalance/httpd-2.2.34/modules/dav/lock
# a modules Makefile has no explicit targets -- they will be defined by
# whatever modules are enabled. just grab special.mk to deal with this.
include $(top_srcdir)/build/special.mk
