top_srcdir   = /home/sekharvaana/Desktop/TomacatLoadbalance/httpd-2.2.34
top_builddir = /home/sekharvaana/Desktop/TomacatLoadbalance/httpd-2.2.34
srcdir       = /home/sekharvaana/Desktop/TomacatLoadbalance/httpd-2.2.34/modules/http
builddir     = /home/sekharvaana/Desktop/TomacatLoadbalance/httpd-2.2.34/modules/http
VPATH        = /home/sekharvaana/Desktop/TomacatLoadbalance/httpd-2.2.34/modules/http

include $(top_srcdir)/build/special.mk

