top_srcdir   = /home/sekharvaana/Desktop/TomacatLoadbalance/httpd-2.2.34
top_builddir = /home/sekharvaana/Desktop/TomacatLoadbalance/httpd-2.2.34
srcdir       = /home/sekharvaana/Desktop/TomacatLoadbalance/httpd-2.2.34/server/mpm
builddir     = /home/sekharvaana/Desktop/TomacatLoadbalance/httpd-2.2.34/server/mpm
VPATH        = /home/sekharvaana/Desktop/TomacatLoadbalance/httpd-2.2.34/server/mpm

SUBDIRS = $(MPM_SUBDIR_NAME)

include $(top_builddir)/build/rules.mk
