top_srcdir   = /home/sekharvaana/Desktop/TomacatLoadbalance/httpd-2.2.34
top_builddir = /home/sekharvaana/Desktop/TomacatLoadbalance/httpd-2.2.34
srcdir       = /home/sekharvaana/Desktop/TomacatLoadbalance/httpd-2.2.34/os/unix
builddir     = /home/sekharvaana/Desktop/TomacatLoadbalance/httpd-2.2.34/os/unix
VPATH        = /home/sekharvaana/Desktop/TomacatLoadbalance/httpd-2.2.34/os/unix

LTLIBRARY_NAME    = libos.la
LTLIBRARY_SOURCES = unixd.c

include $(top_srcdir)/build/ltlib.mk
