top_srcdir   = /home/sekharvaana/Desktop/TomacatLoadbalance/httpd-2.2.34
top_builddir = /home/sekharvaana/Desktop/TomacatLoadbalance/httpd-2.2.34
srcdir       = /home/sekharvaana/Desktop/TomacatLoadbalance/httpd-2.2.34/os
builddir     = /home/sekharvaana/Desktop/TomacatLoadbalance/httpd-2.2.34/os
VPATH        = /home/sekharvaana/Desktop/TomacatLoadbalance/httpd-2.2.34/os

SUBDIRS = $(OS_DIR)

include $(top_builddir)/build/rules.mk
