top_srcdir   = /home/sekharvaana/Desktop/TomacatLoadbalance/httpd-2.2.34
top_builddir = /home/sekharvaana/Desktop/TomacatLoadbalance/httpd-2.2.34
srcdir       = /home/sekharvaana/Desktop/TomacatLoadbalance/httpd-2.2.34/modules/generators
builddir     = /home/sekharvaana/Desktop/TomacatLoadbalance/httpd-2.2.34/modules/generators
VPATH        = /home/sekharvaana/Desktop/TomacatLoadbalance/httpd-2.2.34/modules/generators

include $(top_srcdir)/build/special.mk

